[workspace]
authors = ["Mart√≠ Bosch <marti.bosch@protonmail.com>"]
channels = ["conda-forge"]
name = "_snakemacs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
zmq-build = "cd straight/repos/emacs-zmq && make"

[dependencies]
emacs = ">=30.2,<31"
make = ">=4.4.1,<5"
cmake = ">=4.1.2,<5"
libtool = ">=2.5.4,<3"
autoconf = ">=2.72,<3"
automake = ">=1.17,<2"
pkg-config = ">=0.29.2,<0.30"
compilers = ">=1.11.0,<2"
jupyter = ">=1.1.1,<2"
pixi-kernel = ">=0.6.7,<0.7"
ipykernel = ">=7.1.0,<8"
